volumes:
  postgres_data:

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=minesweeper_db
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minesweeper-network

  server:
    build: ./backend
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=minesweeper_db
      - POSTGRES_PORT=5432
      - DATABASE_HOST=postgresdb
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./backend
        target: /app
    command: npm run start:dev
    networks:
      - minesweeper-network

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./ui
        target: /client
    networks:
      - minesweeper-network

networks:
  minesweeper-network:
    driver: bridge
